spring.application.name=url-service
spring.threads.virtual.enabled=true
# Disable caching for development
spring.thymeleaf.cache=false
# If you use static resources
spring.web.resources.chain.cache=false
spring.devtools.livereload.enabled=true
