spring.application.name=url-service
spring.threads.virtual.enabled=true

# Disable caching for development
spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false
spring.devtools.livereload.enabled=true

# optimizaitons
spring.main.lazy-initialization=true

# database
spring.datasource.url=jdbc:mysql://db.hridaykh.in:3306/UrlDB
spring.datasource.username=${URL_DB_USER}
spring.datasource.password=${URL_DB_PASS}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# error
spring.web.error.whitelabel.enabled=false

# oauth
oauth.sign-key=${OAUTH_SIGN_KEY}
oauth.github.client-id=${OAUTH_GITHUB_CLIENT_ID}
oauth.github.client-secret=${OAUTH_GITHUB_CLIENT_SECRET}
